"""add name

Revision ID: 8f3a7393fcee
Revises: 003cc1760780
Create Date: 2024-07-24 14:42:30.707071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f3a7393fcee'
down_revision: Union[str, None] = '003cc1760780'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('name', sa.String(), nullable=False, server_default='Gocha'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'name')
    # ### end Alembic commands ###
